language: haskell
branches:
  only:
  - master
env:
  global:
  - secure: l++o17MuVtDCjUH3BSWIxQovHaTUpx30FXsj0rH8ff1Ov0UOMWXkNxLf7LM2iB/4boLfmf2L9Rnyv+c9kNN3DyggcrTLtF5kwMgS5ft05l3opErx2xr4zdkT40YQOXFG+u8XIjMq53js67QTF8AhtAO4ZnH+H9x+P4jQJzBwmDA=
install:
- cabal install hakyll
- ghc --make site.hs
script: "./site build"
after_script: bash post_build.sh
