language: haskell
branches: 
  only:
    - master
env:
  global:
    - secure: "pLuY2YdeDRX+bkrpQIMjBMNhh2BOJHXdipO5H5B1Gvf/c3YIF1Q3nYAwcz4FPRlIWRJEjrF3sDtC16/a7b7LGcMNg6TUALDn9YauqajoqAhm+EF2WH+pl6Tda6XN4fxOd+ZSqN3zKp/U4/Q/CJjvErf0St+/6P2jiN3ycEefhgc="
install:
  - cabal install hakyll
  - ghc --make site.hs
before_script:
  - cd _site
  - git checkout master
  - git pull origin master
  - cd ..
script: ./site build
after_script:
  - cd _site
  - git status
  - git add --all
  - git config --global user.email "anthony.r.dipasquale@gmail.com"
  - git config --global user.name "Travis"
  - git commit -m "snapshot $(date '+%m/%d/%y %H:%M')"
  - git push "$REPO_URL" master | grep -v http
  - cd ..
